<?php

/* Honeymoon Israel Custom Module
 * At first, this is generally for Stripe-Drupal integration
 * to run the Registration form. Ultimately, perhaps more?
 */

function bfc_drupal_donate_form_alter(&$form, &$form_state, $form_id) {
	if($form['#form_id'] == "webform_client_form_1") :
		drupal_add_js('https://js.stripe.com/v2/', 'external');
		drupal_add_js(drupal_get_path('module', 'bfc_drupal_donate') . "/bfc_drupal_donate.js", 'file');
		$form['submitted']['payment_information']['credit_card_number']['#attributes']['data-stripe'] = "number";
		$form['submitted']['payment_information']['cvc']['#attributes']['data-stripe'] = "cvc";
		$form['submitted']['payment_information']['expiration_month']['#attributes']['data-stripe'] = "exp_month";
		$form['submitted']['payment_information']['expiration_year']['#attributes']['data-stripe'] = "exp_year";
	endif;
}

?>
